### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by MaxiPy** [SimsumMC/communitybot#1]
https://github.com/SimsumMC/communitybot/blob/a7f2a0940d7bb3430b21ed1796fbb0a51236f5b4/main.py#L57

**Ich habe ein paar Fragen zu deinem Code:**

- Wieso benutzt du für diesen Command keine Command Group?
- Wieso benutzt du überhaupt Aliase für deinen Command, du kannst oben bei `commands.Bot(command_prefix="!", case_insensitive=True)` benutzen, dann ist es egal, wie die Klein- und Großschreibung bei allen Commands ist?

**Comment by SimsumMC** [comment]
1. Was genau meinst du mit Command Group? 2.Da hast du komplett recht, das kannte ich leider noch nicht haha Vielen Dank
